name: roomspot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.2
  loading_animation_widget: ^1.2.0+4
  http: ^1.1.0
  go_router: ^14.1.4
  get: ^4.6.6
  file_picker: ^5.2.10
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/gmail.png
    - assets/icon/registrationIcon.png
    - assets/data/common/user.json
    - assets/data/provider/post.json
